In [ ]:
class Student:
  student_id=0
  def __init__(self,name,dept,age,cgpa):
    self.name=name
    self.dept=dept
    self.age=age
    self.cgpa=cgpa
    Student.student_id+=1

  def showDetails(self):
    print('ID:',self.student_id)
    print('Name:',self.name)
    print('Department:',self.dept)
    print('Age:',self.age)
    print('CGPA:',self.cgpa)
    
  @classmethod
  def from_String(Student,info):
    name,dept,age,cgpa=info.split('-')
    return Student(name,dept,age,cgpa)

s1 = Student("Samin", "CSE", 21, 3.91)
s1.showDetails()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.showDetails()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.showDetails() 
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.showDetails()

ID: 1
Name: Samin
Department: CSE
Age: 21
CGPA: 3.91
-----------------------
ID: 2
Name: Fahim
Department: ECE
Age: 21
CGPA: 3.85
-----------------------
ID: 3
Name: Tahura
Department: EEE
Age: 22
CGPA: 3.01
-----------------------
ID: 4
Name: Sumaiya
Department: BBA
Age: 23
CGPA: 3.96

In [ ]:
class Travel:
  count=0
  def __init__(self,source,dest,time=1):
    self.source=source
    self.dest=dest
    self.time=time
    Travel.count+=1
  
  def set_time(self,time):
    self.time=time
  
  def get_time(self):
    return self.time

  def set_source(self,source):
    self.source=source
  
  def get_source(self):
    return self.source

  def set_destination(self,dest):
    self.dest=dest
  
  def get_destination(self):
    return self.dest

  
  def display_travel_info(self):
    print('Source:',self.source)
    print('Destination:',self.dest)
    return (f'Flight Time: {self.time}:00')
  

print('No. of Traveller =', Travel.count)
print("=======================")
t1 = Travel("Dhaka","India")
print(t1.display_travel_info())
print("=======================")
t2 = Travel("Kuala Lampur","Dhaka")
t2.set_time(23)
print(t2.display_travel_info())
print("=======================")
t3 = Travel("Dhaka","New_Zealand")
t3.set_time(15)
t3.set_destination("Germany")
print(t3.display_travel_info())
print("=======================")
t4 = Travel("Dhaka","India")
t4.set_time(9)
t4.set_source("Malaysia")
t4.set_destination("Canada")
print(t4.display_travel_info())
print("=======================")
print('No. of Traveller =', Travel.count)

No. of Traveller = 0
=======================
Source: Dhaka
Destination: India
Flight Time: 1:00
=======================
Source: Kuala Lampur
Destination: Dhaka
Flight Time: 23:00
=======================
Source: Dhaka
Destination: Germany
Flight Time: 15:00
=======================
Source: Malaysia
Destination: Canada
Flight Time: 9:00
=======================
No. of Traveller = 4

In [ ]:
class Laptop:
   laptopCount=0
   def __init__(self,name,count):
     self.name=name
     self.count=count
     Laptop.laptopCount+=count
   @staticmethod
   def advantage():
     print("Laptops are portable")
   @classmethod
   def resetCount(self):
     Laptop.laptopCount=0

lenovo = Laptop("Lenovo", 5);
dell = Laptop("Dell", 7);
print(lenovo.name, lenovo.count)
print(dell.name, dell.count)
print("Total number of Laptops", Laptop.laptopCount)
Laptop.advantage()
Laptop.resetCount()
print("Total number of Laptops", Laptop.laptopCount)

Lenovo 5
Dell 7
Total number of Laptops 12
Laptops are portable
Total number of Laptops 0

In [ ]:
class Cat:
  Number_of_cats=0
  def __init__(self,color,pos):
    self.color=color
    self.position=pos
    Cat.Number_of_cats+=1

  @classmethod
  def no_parameter(cls):
    return cls("White","sitting")
  @classmethod
  def first_parameter(cls,col):
    return cls(col,'sitting')
  @classmethod
  def second_parameter(cls,pos):
    return cls("Grey",pos)
  def printCat(self):
    print(f'{self.color} cat is {self.position}')
  def changeColor(self,colo):
    self.color=colo


    
print("Total number of cats:", Cat.Number_of_cats)
c1 = Cat.no_parameter()
c2 = Cat.first_parameter("Black")
c3 = Cat("Brown", "jumping")
c4 = Cat("Red", "purring")
c5 = Cat.second_parameter("playing")
print("=======================")
c1.printCat()
c2.printCat()
c3.printCat()
c4.printCat()
c5.printCat()
c1.changeColor("Blue")
c3.changeColor("Purple")
c1.printCat()
c3.printCat()
print("=======================")
print("Total number of cats:", Cat.Number_of_cats)

Total number of cats: 0
=======================
White cat is sitting
Black cat is sitting
Brown cat is jumping
Red cat is purring
Grey cat is playing
Blue cat is sitting
Purple cat is jumping
=======================
Total number of cats: 5

In [ ]:
#HOMEWORKKKKKK::

class Student:
  ID=0
  def __init__(self,name,dept,age,cgpa):
    self.name=name
    self.dept=dept
    self.age=age
    self.cgpa=cgpa
    Student.ID+=1
    self.ID=Student.ID
  
  def showDetails(self):
    print('ID:',self.ID)
    print('Name:',self.name)
    print('Department:',self.dept)
    print('Age:',self.age)
    print('CGPA:',self.cgpa)

  @classmethod
  def from_String(Student,info):
    name,dept,age,cgpa=info.split('-')
    return Student(name,dept,age,cgpa)



s1 = Student("Samin", "CSE", 21, 3.91)
s1.showDetails()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.showDetails()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.showDetails()
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.showDetails()

ID: 1
Name: Samin
Department: CSE
Age: 21
CGPA: 3.91
-----------------------
ID: 2
Name: Fahim
Department: ECE
Age: 21
CGPA: 3.85
-----------------------
ID: 3
Name: Tahura
Department: EEE
Age: 22
CGPA: 3.01
-----------------------
ID: 4
Name: Sumaiya
Department: BBA
Age: 23
CGPA: 3.96

In [ ]:
class Assassin:
  num_assassin=0
  def __init__(self,name,success):
    self.name=name
    self.success=success
    Assassin.num_assassin+=1

  def printDetails(self):
    print('Name:',self.name)
    print(f'Success rate:{self.success}%')
    print('Total number of Assassin:',Assassin.num_assassin)
  
  
  @classmethod
  def failureRate(Assassin,name,num):
    Assassin.name=name
    Assassin.num=num
    successRate=100-num
    return Assassin(Assassin.name,successRate)
  
  @classmethod
  def failurePercentage(Assassin,name,num):
    Assassin.name=name
    Assassin.num=int(num)
    successRate=100-num
    return Assassin(Assassin.name,successRate)
  
john_wick = Assassin('John Wick', 100)
john_wick.printDetails()
print('================================')
nagisa = Assassin.failureRate("Nagisa", 20)
nagisa.printDetails()
print('================================')
akabane = Assassin.failurePercentage("Akabane", "10%")
akabane.printDetails()

Name: John Wick
Success rate:100%
Total number of Assassin: 1
================================
Name: Nagisa
Success rate:80%
Total number of Assassin: 2
================================

ValueError: ignored

In [ ]:
class Passenger:
  count=0
  def __init__(self,name):
    self.name=name
    Passenger.count+=1
  
  def set_bag_weight(self,weight):
    self.weight=weight
    if self.weight<=20:
      self.fare=450
    elif 21<=self.weight<=50:
      self.fare=450+50
    else:
      self.fare=450+100
  
  def printDetail(self):
    print('Name:',self.name)
    print('Bus Fare:',self.fare,'taka')

print('Total Passenger:', Passenger.count)
p1 = Passenger('Jack')
p1.set_bag_weight(90)
p2 = Passenger('Carol')
p2.set_bag_weight(10)
p3 = Passenger('Mike')
p3.set_bag_weight(25)
print("=========================")
p1.printDetail()
print("=========================")
p2.printDetail()
print("=========================")
p3.printDetail()
print("=========================")
print('Total Passenger:', Passenger.count)

Total Passenger: 0
=========================
Name: Jack
Bus Fare: 550 taka
=========================
Name: Carol
Bus Fare: 450 taka
=========================
Name: Mike
Bus Fare: 500 taka
=========================
Total Passenger: 3

In [ ]:
class Travel:
  count=0
  def __init__(self,source,dest,time=1):
    self.source=source
    self.dest=dest
    self.time=time
    Travel.count+=1
  
  def set_time(self,time):
    self.time=time
  
  #def get_time(self):
    #return self.time

  def set_source(self,source):
    self.source=source
  
  #def get_source(self):
    #return self.source

  def set_destination(self,dest):
    self.dest=dest
  
  #def get_destination(self):
    #return self.dest

  
  def display_travel_info(self):
    print('Source:',self.source)
    print('Destination:',self.dest)
    return (f'Flight Time: {self.time}:00')
  

print('No. of Traveller =', Travel.count)
print("=======================")
t1 = Travel("Dhaka","India")
print(t1.display_travel_info())
print("=======================")
t2 = Travel("Kuala Lampur","Dhaka")
t2.set_time(23)
print(t2.display_travel_info())
print("=======================")
t3 = Travel("Dhaka","New_Zealand")
t3.set_time(15)
t3.set_destination("Germany")
print(t3.display_travel_info())
print("=======================")
t4 = Travel("Dhaka","India")
t4.set_time(9)
t4.set_source("Malaysia")
t4.set_destination("Canada")
print(t4.display_travel_info())
print("=======================")
print('No. of Traveller =', Travel.count)

No. of Traveller = 0
=======================
Source: Dhaka
Destination: India
Flight Time: 1:00
=======================
Source: Kuala Lampur
Destination: Dhaka
Flight Time: 23:00
=======================
Source: Dhaka
Destination: Germany
Flight Time: 15:00
=======================
Source: Malaysia
Destination: Canada
Flight Time: 9:00
=======================
No. of Traveller = 4

In [ ]:
class Employee:
  def __init__(self,name,workingPeriod):
    self.name=name
    self.workingPeriod=workingPeriod
  
  @classmethod
  def employeeByJoiningYear(Employee,name,year):
    Employee.name=name
    workingPeriod=2022-year
    Employee.workingPeriod=workingPeriod
    return Employee(Employee.name,Employee.workingPeriod)

  @staticmethod
  def experienceCheck(workingPeriod,gender):
    if gender=='male':
      x='He'
    else:
      x="She"

    if workingPeriod<3:
      return f'{x} is not experienced'
    else:
      return f'{x} is experienced ' 
    
employee1 = Employee('Dororo', 3)
employee2 = Employee.employeeByJoiningYear('Harry', 2016)
print(employee1.workingPeriod)
print(employee2.workingPeriod)
print(employee1.name)
print(employee2.name)
print(Employee.experienceCheck(2, "male"))
print(Employee.experienceCheck(3, "female"))

3
6
Dororo
Harry
He is not experienced
She is experienced

In [ ]:
class Laptop:
  laptopCount=0
  def __init__(self,name,count):
    self.name=name
    self.count=count
    Laptop.laptopCount+=count

  @classmethod
  def advantage(Laptop):
    print('Laptops are portable')
  
  @staticmethod
  def resetCount():
    Laptop.laptopCount=0

lenovo = Laptop("Lenovo", 5);
dell = Laptop("Dell", 7);
print(lenovo.name, lenovo.count)
print(dell.name, dell.count)
print("Total number of Laptops", Laptop.laptopCount)
Laptop.advantage()
Laptop.resetCount()
print("Total number of Laptops", Laptop.laptopCount)

Lenovo 5
Dell 7
Total number of Laptops 12
Laptops are portable
Total number of Laptops 0

In [ ]:
class Cat:
  Number_of_cats=0
  def __init__(self,color,act):
    self.color=color
    self.act=act
    Cat.Number_of_cats+=1

  @classmethod
  def no_parameter(Cat):
    return Cat('white','sitting')

  @classmethod
  def first_parameter(Cat,col):
    return Cat(col,'sitting')
  
  @classmethod
  def second_parameter(Cat,act):
    return Cat('Grey',act)
  
  def printCat(self):
    print(f'{self.color} cat is {self.act}')
  
  def changeColor(self,colr):
    self.color=colr


print("Total number of cats:", Cat.Number_of_cats)
c1 = Cat.no_parameter()
c2 = Cat.first_parameter("Black")
c3 = Cat("Brown", "jumping")
c4 = Cat("Red", "purring")
c5 = Cat.second_parameter("playing")
print("=======================")
c1.printCat()
c2.printCat()
c3.printCat()
c4.printCat()
c5.printCat()
c1.changeColor("Blue")
c3.changeColor("Purple")
c1.printCat()
c3.printCat()
print("=======================")
print("Total number of cats:", Cat.Number_of_cats)

Total number of cats: 0
=======================
white cat is sitting
Black cat is sitting
Brown cat is jumping
Red cat is purring
Grey cat is playing
Blue cat is sitting
Purple cat is jumping
=======================
Total number of cats: 5

In [ ]:
class Cylinder:
  height=18
  radius=5
  def __init__(self,radius,height):
    print(f'Default radius={Cylinder.radius} and height={Cylinder.height}.')
    self.radius=radius
    self.height=height
    print(f'Updated: radius={self.radius} and height={self.height}.')
    Cylinder.radius=self.radius
    Cylinder.height=self.height
  
  @classmethod
  def swap (cls, height, radius):
      obj = cls(radius, height)
      return obj
  

  @classmethod
  def changeFormat(cls,info):
    radius,height=info.split('-')
    obj=cls(float(radius),float(height))
    return obj

  @staticmethod
  def area(radius,height):
    import math
    a=(2*math.pi*radius**2)+(2*math.pi*radius*height)
    print('Area:',a)

  @staticmethod
  def volume(radius,height):
    import math
    v=(math.pi*radius**2*height)
    print('Volume:',v)


c1 = Cylinder(0,0)
Cylinder.area(c1.radius,c1.height)
Cylinder.volume(c1.radius,c1.height)
print("===============================")
c2 = Cylinder.swap(8,3)
c2.area(c2.radius,c2.height)
c2.volume(c2.radius,c2.height)
print("===============================")
c3 = Cylinder.changeFormat("7-13")
c3.area(c3.radius,c3.height)
c3.volume(c3.radius,c3.height)
print("===============================")
Cylinder(0.3,5.56).area(Cylinder.radius,Cylinder.height)
print("===============================")
Cylinder(3,5).volume(Cylinder.radius,Cylinder.height)

Default radius=5 and height=18.
Updated: radius=0 and height=0.
Area: 0.0
Volume: 0.0
===============================
Default radius=0 and height=0.
Updated: radius=3 and height=8.
Area: 207.34511513692635
Volume: 226.1946710584651
===============================
Default radius=3 and height=8.
Updated: radius=7.0 and height=13.0.
Area: 879.645943005142
Volume: 2001.1945203366981
===============================
Default radius=7.0 and height=13.0.
Updated: radius=0.3 and height=5.56.
Area: 11.045839770021713
===============================
Default radius=0.3 and height=5.56.
Updated: radius=3 and height=5.
Volume: 141.3716694115407

In [ ]:
class Student:
  Total_Student = 0
  BRAC_University_Student = 0
  Other_Institution_Student = 0
  def __init__(self,name,dept,inst='BRAC University'):
    self.name=name
    self.dept=dept
    self.inst=inst
    Student.Total_Student+=1
    if inst=='BRAC University':
      Student.BRAC_University_Student+=1
    else:
      Student.Other_Institution_Student+=1
  
  @classmethod
  def printDetails(Student):
    print('Total Student(s):',Student.Total_Student)
    print('BRAC University Student(s):',Student.BRAC_University_Student)
    print('Other Institution Student(s):',Student.Other_Institution_Student)

  @classmethod
  def createStudent(Student,name,dept,inst='BRAC University'):
    Student.name=name
    Student.dept=dept
    Student.inst=inst
    return Student(Student.name,Student.dept,Student.inst)
  
  def individualDetail(self):
    print("Name:",self.name)
    print("Department: ",self.dept)
    print("Institution:",self.inst)


Student.printDetails()
print('#########################')
mikasa = Student('Mikasa Ackerman', "CSE")
mikasa.individualDetail()
print('------------------------------------------')
Student.printDetails()
print('========================')
harry = Student.createStudent('Harry Potter', "Defence Against Dark Arts", "Hogwarts School")
harry.individualDetail()
print('-------------------------------------------')
Student.printDetails()
print('=========================')
levi = Student.createStudent("Levi Ackerman", "CSE")
levi.individualDetail()
print('--------------------------------------------')
Student.printDetails()

Total Student(s): 0
BRAC University Student(s): 0
Other Institution Student(s): 0
#########################
Name: Mikasa Ackerman
Department:  CSE
Institution: BRAC University
------------------------------------------
Total Student(s): 1
BRAC University Student(s): 1
Other Institution Student(s): 0
========================
Name: Harry Potter
Department:  Defence Against Dark Arts
Institution: Hogwarts School
-------------------------------------------
Total Student(s): 2
BRAC University Student(s): 1
Other Institution Student(s): 1
=========================
Name: Levi Ackerman
Department:  CSE
Institution: BRAC University
--------------------------------------------
Total Student(s): 3
BRAC University Student(s): 2
Other Institution Student(s): 1

In [ ]:
class SultansDine:
  Total_Number_of_branch=0
  Total_Sell=0
  def __init__(self,branch):
    self.branch=branch
    SultansDine.Total_Number_of_branch+=1
  
  




SultansDine.details()
print('########################')
dhanmodi = SultansDine('Dhanmondi')
dhanmodi.sellQuantity(25)
dhanmodi.branchInformation()
print('-----------------------------------------')
SultansDine.details()
print('========================')
baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()
print('========================')
gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()